FROM debian:12 AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake

WORKDIR /app
COPY . .

RUN mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc) && \
    cpack -G DEB

FROM debian:12

RUN apt-get update && apt-get install -y man man-db less

COPY --from=builder /app/build/out/*.deb /tmp/

RUN dpkg -i /tmp/*.deb && rm -rf /tmp/*.deb

RUN groupadd unprivileged-group && \
    useradd -g unprivileged-group -N -m unprivileged-user
WORKDIR /home/unprivileged-user
USER unprivileged-user:unprivileged-group
