FROM fedora:42 AS builder

RUN dnf install -y \
    gcc-c++ \
    cmake \
    make \
    rpm-build

WORKDIR /app
COPY . .

RUN mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc) && \
    cpack -G RPM

FROM fedora:42

RUN dnf install -y man man-pages man-db less --setopt='tsflags='

COPY --from=builder /app/build/out/*.rpm /tmp/

RUN dnf install -y /tmp/*.rpm --setopt='tsflags=' && \
    rm -rf /tmp/*.rpm

RUN groupadd unprivileged-group && \
    useradd -g unprivileged-group -N -m unprivileged-user
WORKDIR /home/unprivileged-user
USER unprivileged-user:unprivileged-group
