FROM fedora:42

COPY ../build/out/*.rpm .
RUN dnf install -y $(ls *.rpm | head -n1) && rm -rf ./*.rpm

RUN groupadd unprivileged-group && \
    useradd -g unprivileged-group -N -m unprivileged-user
WORKDIR /home/unprivileged-user
USER unprivileged-user:unprivileged-group
