FROM ubuntu:24.04

COPY ../build/out/*.deb .
RUN dpkg -i $(ls *.deb | head -n1) && rm -f ./*.deb

RUN groupadd unprivileged-group && \
    useradd -g unprivileged-group -N -m unprivileged-user
WORKDIR /home/unprivileged-user
USER unprivileged-user:unprivileged-group
