#include <iostream>
#include <getopt.h>
#include "prng.hpp"
#include "linear_congruential_generator.hpp"
#include "xorshift.hpp"
#include "program_runner.hpp"


struct Range {
    int min;
    int max;
};

Range get_range_from_args(int argc, char **argv){
    if (argc != 3){
        throw std::invalid_argument("Incorrect number of arguments. ");
    }

    std::string min_str = std::string(argv[1]);
    std::string max_str = std::string(argv[2]);

    // can throw an exception
    Range range;
    range.min = std::stoi(min_str);
    range.max = std::stoi(max_str);
    return range;
}

void print_help_message(){
    std::string_view help = "Usage: randomizer <min> <max>\n";
    std::cout << help << std::endl;
}


int main(int argc, char *argv[]){
    // Range range;
    // try {
    //      range = get_range_from_args(argc, argv);
    // } catch (std::invalid_argument& e){
    //     print_help_message();
    //     exit(1);
    // } catch (std::out_of_range& e){
    //     print_help_message();
    //     exit(1);
    // }

    // auto xorshift = XORShift();


    // std::cout << "Random number between " << range.min << " and " << range.max << "\n";

    // std::cout << xorshift.generateUnitNormalRandomValue() << " was a pseudorandom number generated by the xorshift.\n";
    // std::cout << xorshift.generateUnitNormalRandomValue() << " was a pseudorandom number generated by the xorshift.\n";
    // std::cout << xorshift.generateUnitNormalRandomValue() << " was a pseudorandom number generated by the xorshift.\n";

    ProgramRunner runner = ProgramRunner(argc, argv);


    return 0;
    
}